import { getSpotifyUserId } from './_lib/spotify.js'

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' })
  }

  const authHeader = req.headers.authorization
  if (!authHeader?.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Missing access token' })
  }

  const accessToken = authHeader.slice(7)
  const { trackUris } = req.body

  if (!trackUris || !Array.isArray(trackUris) || trackUris.length === 0) {
    return res.status(400).json({ error: 'trackUris array is required' })
  }

  try {
    const userId = await getSpotifyUserId(accessToken)

    // Create playlist
    const today = new Date().toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
    })

    const createRes = await fetch(
      `https://api.spotify.com/v1/users/${userId}/playlists`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name: `Today's Playlist — ${today}`,
          description: `Songs picked for ${today} based on music history, birthdays, and today's events. Generated by todaysplaylist.com`,
          public: false,
        }),
      }
    )

    if (!createRes.ok) {
      const errText = await createRes.text()
      console.error('Create playlist failed:', errText)
      return res.status(502).json({ error: 'Failed to create Spotify playlist' })
    }

    const playlist = await createRes.json()

    // Add tracks to playlist (Spotify allows max 100 per request)
    const addRes = await fetch(
      `https://api.spotify.com/v1/playlists/${playlist.id}/tracks`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ uris: trackUris }),
      }
    )

    if (!addRes.ok) {
      const errText = await addRes.text()
      console.error('Add tracks failed:', errText)
      return res.status(502).json({ error: 'Failed to add tracks to playlist' })
    }

    res.json({
      playlistUrl: playlist.external_urls.spotify,
      playlistId: playlist.id,
      trackCount: trackUris.length,
    })
  } catch (err) {
    console.error('Playlist creation error:', err)
    res.status(500).json({ error: 'Server error' })
  }
}
